### PR TITLE
fix: properly handle @media in __resetStyles()

### LINKED ISSUE #321: webpack-extraction-plugin: @media in __resetStyles() creates broken CSS
`@griffel/webpack-extraction-plugin` produces invalid CSS when `__resetStyles()` contains a `@media` rule.

### Input

```ts
import { __resetStyles } from "@griffel/react";
export const useClassName = /*#__PURE__*/ __resetStyles("r13wlxb8", null, [
  ".r13wlxb8{line-height:0;}",
  "@media screen and (prefers-reduced-motion: reduce){.r13wlxb8{transition-duration:0.01ms;}}"
]);
```

### Expected output

```css
.r13wlxb8 {
  line-height: 0;
}
@media screen and (prefers-reduced-motion: reduce) {
  .r13wlxb8 {
    transition-duration: 0.01ms;
  }
}, /* 👈 "," at end */
```

```
    SyntaxError: CssSyntaxError: Unknown word (3:116)
      1 |
      2 | /** griffel.css **/
    > 3 | .r13wlxb8{line-height:0;}@media screen and (prefers-reduced-motion: reduce){.r13wlxb8{transition-duration:0.01ms;}},
        |                                                                                                                    ^

      179 |
      180 |       resultCSS = fixLineEndings(
    > 181 |         prettier.format(result.cssOutput, {
          |                  ^
      182 |           ...prettierConfig,
      183 |           parser: 'css',
      184 |         }),
```

### Expected output

```css
.r13wlxb8 {
  line-height: 0;
}
@media screen and (prefers-reduced-motion: reduce) {
  .r13wlxb8 {
    transition-duration: 0.01ms;
  }
}
```

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #321.

### CODE REVIEW

File: packages/webpack-extraction-plugin/src/parseCSSRules.ts [hunk 1]
```diff
@@ -37,7 +37,7 @@ export function parseCSSRules(css: string) {
 
     if (cssBucketName) {
       const cssRule = serialize([element], stringify);
-      const bucketEntry: CSSBucketEntry = element.type === MEDIA ? [cssRule, cssMeta!] : cssRule;
```
Comment (layershifter) [inline packages/webpack-extraction-plugin/src/parseCSSRules.ts:40]: This condition was not safe as only rules from `m` bucket have `cssMeta` information.

File: packages/webpack-extraction-plugin/src/parseCSSRules.ts [hunk 2]
```diff
@@ -37,7 +37,7 @@ export function parseCSSRules(css: string) {
...
+      const bucketEntry: CSSBucketEntry = cssBucketName === 'm' ? [cssRule, cssMeta!] : cssRule;
```
Comment (miroslavstastny) [inline packages/webpack-extraction-plugin/src/parseCSSRules.ts:40]: The GitHub actions warning is really hidden here. Can we consider to complain more visibly?

Comment (layershifter) [reply packages/webpack-extraction-plugin/src/parseCSSRules.ts:40]: Good call, did not even notice it. Now the rule will throw
