### PR TITLE
fix(core): trim ">" selector

### LINKED ISSUE #431: Selector `>` and `> ` should generate same class name
### Actual behavior:
[griffel playground](https://griffel.js.org/try-it-out/?code=JYWwDg9gTgLgBAbziAhgawKYGUYE8A2GAzgDRxEAW0MFKAdgCZFwC%2BcAZlBCHAOQACAcyjB27DPgD0AY2gZeAbgBQSjAA9IsOAwzsUAV3zxUmHAWIAKBErhwuEGAC5EN23wBkAPgB0MYjF5nJFl8aGdeYQwMOl5WEldbXi84X39AxDgQsL5I6NiWVxZ4lgBKZSA):
 
image

Note that `>` and `> ` selector generates different classNames.

### Expected behavior: 
Note that `>` and `> ` selector generates the same className

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #431.

This PR updates hash generation for properties and classes to trim selectors before hash will be generated. Currently only the case with `> ` is handled.

New tests added for matching scenarios.

### CODE REVIEW

File: packages/core/src/runtime/utils/trimSelector.ts [hunk 1]
```diff
@@ -0,0 +1,6 @@
+/**
+ * Trims selectors to generate consistent hashes.
+ */
+export function trimSelector(selector: string): string {
```
Comment (ling1726) [inline packages/core/src/runtime/utils/trimSelector.ts:4]: for me it's a little bit more than a nit since what you're doing here isn't actually trimming. Youre're specifically targeting the spaces after the `>` combinator.

I'd rename this to `stripExtraWhitespace` and add some extra documentation why that specifically is necessary

**Review by ling1726 — APPROVED** [review]

File: packages/core/src/runtime/utils/trimSelector.ts (hunk 1 above)
Comment (layershifter) [reply packages/core/src/runtime/utils/trimSelector.ts:4]: Potentially we could have more cases, that's why I went with more general naming.
