### PR TITLE
fix(core): fix hash collisions with at rules

### LINKED ISSUE #559: core: hashes for @media & @container can collide
Hello! 

Recently run into an issue with the combination of @media and @container queries. Currently on griffel/core 1.15.2 via @fluentui/react-components

What I'm running into is that if a @container query matches the @media query, they get flattened into a single @media query. 

Example of just a @container query - correct  

image

Then adding an @media query then combines them both into an @media query

image

Made a codesandbox here to be able to [repro in isolation](https://codesandbox.io/p/devbox/fluentui-container-queries-twz6v8?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwfekus400073p6o1pknnm1x%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwfekus400023p6orzw1myko%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwfekus400043p6opqxu7ezc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwfekus400063p6or837h2yu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B57.081046723356984%252C42.918953276643016%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwfekus400023p6orzw1myko%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwfekus400013p6o16qffoym%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwfekus400023p6orzw1myko%2522%252C%2522activeTabId%2522%253A%2522clwfekus400013p6o16qffoym%2522%257D%252C%2522clwfekus400063p6or837h2yu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwfekus400053p6ozvt9d8uv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwfekus400063p6or837h2yu%2522%252C%2522activeTabId%2522%253A%2522clwfekus400053p6ozvt9d8uv%2522%257D%252C%2522clwfekus400043p6opqxu7ezc%2522%253A%257B%2522id%2522%253A%2522clwfekus400043p6opqxu7ezc%2522%252C%2522activeTabId%2522%253A%2522clwfeqenx00au3p6oyuxymxyw%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwfekus400033p6oarldwbco%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clwfeqenx00au3p6oyuxymxyw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clwfeqeu0007fdcipc4ie59zz%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A21.016042780748663%257D)

Let me know if there's anything else I can provide to help debug! Thank you in advance!

### LINKED ISSUE #561: core: @layer is not part of property hash
```ts
const useClasses = makeStyles({
  root: {
    color: 'red',
  },
  rootWithLayer: {
    '@layer foo': {
      color: 'red',
    },
  },
});
```

Both `color: red` will have the same hash, this will cause collisions during merging.

https://stackblitz.com/edit/vitejs-vite-lvmmff

### PR DESCRIPTION
**Pull request by layershifter**
See issues for reproductions:
- Fixes #559
- Fixes #561

Adds prefixes for at rules in hashes so they will be unique.

### CODE REVIEW

**Review by ling1726 — APPROVED** [review]

File: packages/core/src/runtime/utils/hashPropertyKey.ts [hunk 1]
```diff
@@ -3,9 +3,22 @@ import hash from '@emotion/hash';
...
 import type { AtRules } from './types';
 
+function addAtRulePrefix(atRule: string, prefix: string): string {
+  return atRule ? prefix + atRule : atRule;
+}
+
+export function atRulesToString(atRules: AtRules): string {
+  return (
+    addAtRulePrefix(atRules.container, 'c') +
+    addAtRulePrefix(atRules.media, 'l') +
```
Comment (ling1726) [inline packages/core/src/runtime/utils/hashPropertyKey.ts:13]:
```suggestion
    addAtRulePrefix(atRules.media, 'm') +
```

File: packages/core/src/runtime/utils/hashPropertyKey.ts [hunk 2]
```diff
@@ -3,9 +3,22 @@ import hash from '@emotion/hash';
...
+    addAtRulePrefix(atRules.layer, 'l') +
+    addAtRulePrefix(atRules.supports, 's')
+  );
+}
+
 export function hashPropertyKey(selector: string, property: string, atRules: AtRules): PropertyHash {
   // uniq key based on property & selector, used for merging later
-  const computedKey = selector + atRules.container + atRules.media + atRules.supports + property;
+  const computedKey = selector + atRulesToString(atRules) + property;
```
Comment (ling1726) [inline packages/core/src/runtime/utils/hashPropertyKey.ts:21]: previously layer queries were not supported in `hashPropertyKey` I guess it was unintentional?

Comment (layershifter) [reply packages/core/src/runtime/utils/hashPropertyKey.ts:21]: No, it's a bug https://github.com/microsoft/griffel/issues/561.
