### PR TITLE
fix: handle multiple url()

### LINKED ISSUE #238: babel-preset: does not handle multiple url()
## Versions 

`@griffel/babel-preset@1.3.7`

## Issue

_Raised by @yume-chan in https://github.com/microsoft/griffel/pull/234#issuecomment-1262265035._

Our `@griffel/babel-preset` doesn't handle multiple URLs in a string: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Using_multiple_backgrounds

#### Input

```ts
import { makeStyles } from '@griffel/react';

import blank from './blank.jpg';
import empty from './empty.jpg';

export const useStyles = makeStyles({
  root: { backgroundImage: `url(${blank}), url(${empty})` },
});
```

#### Output 🚨

```ts
import _asset from './empty.jpg';
import { __styles } from '@griffel/react';
import blank from './blank.jpg';
import empty from './empty.jpg';
export const useStyles = __styles(
  {
    root: {
      Bcmaq0h: 'f1t88go',
    },
  },
  {
    d: [`.f1t88go{background-image:url(./blank.jpg),url(${_asset});}`],
    //                             💥 "./blank.jpg" should be an import
  },
);
```

#### Expected output

```ts
import _asset2 from './empty.jpg';
import _asset from './blank.jpg';
import { __styles } from '@griffel/react';
import blank from './blank.jpg';
import empty from './empty.jpg';
export const useStyles = __styles(
  {
    root: {
      Bcmaq0h: 'classname',
    },
  },
  {
    d: [`.classname{background-image:url(${_asset}),url(${_asset2});}`],
  },
);
```

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #238. _See the bug for the issue description in detail._

The main change is that we use `tokenize` from `stylis` instead of regexps. This is more robust and allows to parse multiple `url()` expressions.

`@griffel/babel-preset` and `@griffel/webpack-extraction-plugin` were updated/adjusted to handle this scenario.

### CODE REVIEW

File: packages/babel-preset/src/assets/isAssetUrl.ts [hunk 1]
```diff
@@ -0,0 +1,3 @@
+export function isAssetUrl(value: string): boolean {
```
Comment (layershifter) [inline packages/babel-preset/src/assets/isAssetUrl.ts:1]: I intentionally didn't cover this by tests directly as it will be changed/removed in #234.

File: packages/babel-preset/src/assets/normalizeStyleRules.ts [hunk 2]
```diff
@@ -22,16 +24,19 @@ export function normalizeStyleRule(
     return ruleValue;
   }
 
-  const result = parseStringWithUrl(ruleValue);
-  // Quotes in URL are optional, so we can also normalize them
-  // https://www.w3.org/TR/CSS2/syndata.html#value-def-uri
-  const url = result.url.replace(/['|"](.+)['|"]/, '$1');
+  return tokenize(ruleValue).reduce((result, token, index, array) => {
```
Comment (layershifter) [inline packages/babel-preset/src/assets/normalizeStyleRules.ts:27]: Instead of a regex I am using `tokenize()` from stylis so we can parse all `url()` entries properly.

File: packages/babel-preset/src/transformPlugin.test.ts [hunk 3]
```diff
@@ -35,11 +35,6 @@ pluginTester({
     // Fixtures
     //
     //
-    {
-      title: 'assets import handling',
-      fixture: path.resolve(fixturesDir, 'assets', 'code.ts'),
-      outputFixture: path.resolve(fixturesDir, 'assets', 'output.ts'),
-    },
```
Comment (layershifter) [inline packages/babel-preset/src/transformPlugin.test.ts:42]: Moved into a separate group.

File: packages/webpack-extraction-plugin/src/babelPluginStripGriffelRuntime.ts [hunk 4]
```diff
@@ -121,54 +121,56 @@ export const babelPluginStripGriffelRuntime = declare<
...
-                    t.stringLiteral(
-                      // When imports are inlined, we need to adjust the relative paths inside url(..) expressions
-                      // to allow css-loader resolve an imported asset properly
-                      transformUrl(
-                        state.filename!,
-                        options.resourceDirectory!,
-                        importDeclarationPath.get('source').node.value,
+                  const expressionPaths = literalPath.get('expressions');
+
+                  expressionPaths.map(expressionPath => {
```
Comment (layershifter) [inline packages/webpack-extraction-plugin/src/babelPluginStripGriffelRuntime.ts:126]: The inner part is 100% percent: now we parse all expressions instead of only first.

File: packages/babel-preset/src/assets/replaceAssetsWithImports.ts [hunk 5]
```diff
@@ -29,6 +30,39 @@ export function replaceAssetsWithImports(
     return assetIdentifiers.get(assetPath) as t.Identifier;
   }
 
+  function buildTemplateLiteralFromValue(value: string): t.TemplateLiteral {
+    const tokens = tokenize(value);
+
+    const quasis: t.TemplateElement[] = [];
```
Comment (ling1726) [inline packages/babel-preset/src/assets/replaceAssetsWithImports.ts:36]: what are quasis ?

Comment (layershifter) [reply packages/babel-preset/src/assets/replaceAssetsWithImports.ts:36]: It's how Babel names string in template literals i.e. `foo` from `foo${bar}`:

image

https://babeljs.io/docs/en/babel-types#templateliteral

File: packages/babel-preset/src/assets/replaceAssetsWithImports.ts [hunk 6]
```diff
@@ -29,6 +30,39 @@ export function replaceAssetsWithImports(
...
+    const expressions: t.Identifier[] = [];
+
+    let acc = '';
+
+    for (let i = 0, l = tokens.length; i < l; i++) {
+      for (; i < l; i++) {
+        acc += tokens[i];
+
+        if (tokens[i] === 'url') {
+          const url = tokens[i + 1].slice(1, -1);
```
Comment (ling1726) [inline packages/babel-preset/src/assets/replaceAssetsWithImports.ts:46]: why ignore the first and last characters of a url ?

Comment (ling1726) [reply packages/babel-preset/src/assets/replaceAssetsWithImports.ts:46]: I'm going by your example of tokens: `('.foo', '{', 'url', 'image.png', '}')`

Comment (yume-chan) [reply packages/babel-preset/src/assets/replaceAssetsWithImports.ts:46]: The first and last characters are parens. `url(image.png)` tokenizes to `["url", "(image.png)"]`

File: packages/babel-preset/src/assets/replaceAssetsWithImports.ts [hunk 7]
```diff
@@ -29,6 +30,39 @@ export function replaceAssetsWithImports(
...
+            acc = ')';
+            i++;
+
+            break;
+          }
+        }
+      }
+    }
+
+    quasis.push(t.templateElement({ raw: acc }, true));
```
[the remark this answers is not in the document]
Comment (ling1726) [reply packages/babel-preset/src/assets/replaceAssetsWithImports.ts:61]: I can't think of much better....

but I don't quite understand why you need the second nested loop, once you find the `url` token you break out of the inner loop and the outer one continues where the inner one left off anyway ??

**Review by ling1726 — APPROVED** [review]
I have doubts about the ugly nested loop in the preset, but otherwise LGTM

File: packages/babel-preset/src/assets/replaceAssetsWithImports.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (layershifter) [reply packages/babel-preset/src/assets/replaceAssetsWithImports.ts]: > but I don't quite understand why you need the second nested loop, once you find the `url` token you break out of the inner loop and the outer one continues where the inner one left off anyway ??

Good catch, it's a leftover from the previous attempt. Removed.
